version: "3.8"

services:
  website:
    extends:
      file: docker-compose.yml
      service: website
    command: gunicorn -b 0.0.0.0:80 app:app
    environment:
      - ENV=prod
    ports:
      - "80:80"
  database:
    extends:
      file: docker-compose.yml
      service: database
  
volumes:
  database-volume: