version: "3.8"

services:
  website:
    build:
      context: .
      dockerfile: ./Dockerfile
    working_dir: /app
    env_file: .env
    environment:
      - ENV=dev
    volumes:
      - "./:/app"
    ports:
      - "5000:5000"
    depends_on:
      - database
   
  database:
    image: postgres:15-alpine
    volumes:
      - "database-volume:/var/lib/postgresql/data"
    env_file: .env

volumes:
  database-volume: