version: "3.8"

services:
  website:
    extends:
      file: docker-compose.yml
      service: website
    command: gunicorn -b 0.0.0.0:8000 app:app
    environment:
      - ENV=prod
    expose:
      - 8000
  database:
    extends:
      file: docker-compose.yml
      service: database
  
volumes:
  database-volume: